# Generated by Django 5.0.6 on 2024-06-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('authorid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('bookid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='publishers',
            fields=[
                ('publisherid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
