# Generated by Django 5.0.6 on 2024-06-23 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_authors_authorid_alter_books_bookid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='publishers',
            new_name='Publisher',
        ),
        migrations.DeleteModel(
            name='authors',
        ),
    ]
